item { 
	name:'Hello'
	id:1
}
item { 
	name:'Good Bye'
	id:2
}
item { 
	name:'I'
	id:3
}
item { 
	name:'You'
	id:4
}
item { 
	name:'Yes'
	id:5
}
item { 
	name:'No'
	id:6
}
item { 
	name:'Help'
	id:7
}
item { 
	name:'Please'
	id:8
}
item { 
	name:'Sorry'
	id:9
}
item { 
	name:'Thanks'
	id:10
}
item { 
	name:'Excuse Me'
	id:11
}
item { 
	name:'I Love You'
	id:12
}
item { 
	name:'What?'
	id:13
}
item { 
	name:'How Are You?'
	id:14
}
item { 
	name:'Eat'
	id:15
}
item { 
	name:'Im Fine'
	id:16
}
item { 
	name:'Name'
	id:17
}
item { 
	name:'Zero'
	id:18
}
item { 
	name:'One'
	id:19
}
item { 
	name:'Two'
	id:20
}
item { 
	name:'Three'
	id:21
}
item { 
	name:'Four'
	id:22
}
item { 
	name:'Five'
	id:23
}
item { 
	name:'Six'
	id:24
}
item { 
	name:'Seven'
	id:25
}
item { 
	name:'Eight'
	id:26
}
item { 
	name:'Nine'
	id:27
}
item { 
	name:'Ten'
	id:28
}
